[project]
name = "zeed"
version = "0.1.0"
description = "Python包管理工具"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "xdeliver", email = "xdeliver@163.com" }
]
dependencies = [
    "click>=8.0.0",
]

[project.scripts]
zeed = "zeed:main"
